### ISSUE TITLE
How do you calculate accuracy and score

### ISSUE THREAD

**Issue by hiteshvaidya** [shivgarg/twitter-sentiment#1]
Hey,

You have mentioned functions like confusion_matrix, f1_score, score etc. But there are definitions of these functions, neither they have been imported as modules. So could you please specify how do you get their outputs?

Thanks

**Comment by shivgarg** [comment]
Check this line. Here all the metric evaluators are imported.
https://github.com/shivgarg/twitter-sentiment/blob/4fbde28fb7b21443f60723e9f309b1d10b7b1a16/train.py#L16
